TRAIN:
  ENABLE: False
  DATASET: Egtea
  BATCH_SIZE: 1
  CHECKPOINT_FILE_PATH: ""
TEST:
  ENABLE: True
  DATASET: Egtea
  BATCH_SIZE: 1
  CHECKPOINT_FILE_PATH: ""
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
MODEL:
  MODEL_NAME: DINOv3_ARHeatmapGazeTemplate
  LOSS_FUNC: kldiv
  DROPOUT_RATE: 0.0
  HEATMAP_SIZE: 64
  USE_HEAD_PROMPTING: False
  USE_TEMPLATE_TOKENS: True
  TEMPLATE_SCALES: [0.25]
  TEMPLATE_USE_GAZE_CENTER: True
  USE_TOKEN_TYPE_EMBED: True
  USE_TEMPORAL_EMBED: True
DEMO:
  ENABLE: True
  WEBCAM: 0
  DISPLAY_WIDTH: 640
  DISPLAY_HEIGHT: 480
